#!/bin/bash
if [ -f ./env/bin/activate ]; then
  source ./env/bin/activate
fi

cd ./app
env FLASK_APP=app.py \
  FLASK_DEBUG=true \
  MONGODB_HOSTNAME='localhost' \
  MONGODB_DATABASE='tiny-url' \
  python app.py